### ISSUE TITLE
UI elements go wack if window size is too small

### ISSUE THREAD

**Issue by mygizli04** [DiscStrad/minetron#3]
![image](https://user-images.githubusercontent.com/42012824/114268390-df83a400-9a11-11eb-8c6c-37265e3fc400.png)

Consider making a minimum size for the window
![image](https://user-images.githubusercontent.com/42012824/114268403-ee6a5680-9a11-11eb-8a38-1a1724c5a755.png)

**Comment by DiscStrad** [comment]
alright I will start working on this right now
